project:
  type: website
  output-dir: docs

website:
  title: "felipelamarca@website/"
  navbar:
    left:
      - href: index.qmd
        text: about-me
      - href: my-work/my-work.qmd
        text: my-work
      - href: projects/projects.qmd
        text: projects
      - href: publications/publications.qmd
        text: publications
      - href: news/news.qmd
        text: news
      - href: posts/posts.qmd
        text: posts
      - href: https://drive.google.com/file/d/1-gCNDi-t3uZO87_fVRIEpkCRfN3o18Zd/view
        text: cv
        
format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



