---
title: "📰News"
---

**December 13, 2024**  
I have been accepted to pursue a Master's degree in Applied Mathematics and Data Science at the [School of Applied Mathematics](https://emap.fgv.br/en) (FGV EMAp). Even though I'm not accepting the offer, I'm very grateful for the opportunity and excited to continue my journey in Political Science at [IESP-UERJ](https://www.iesp.uerj.br/).

**November 26, 2024**  
I have successfully delivered my undergraduate thesis, marking the official completion of my dual degrees in Data Science & Artificial Intelligence from the [School of Applied Mathematics](https://emap.fgv.br/en) (FGV EMAp) and Social Sciences from the [Superior School of Social Sciences](https://cpdoc.fgv.br/en) (FGV CPDOC). I'm very grateful for the support of my family, friends, and advisors throughout this journey, which I'm very proud of.

**November 21, 2024**  
I have been [accepted](https://iesp.uerj.br/wp-content/uploads/2024/11/Aprovados-por-ordem-de-classificacao-Ciencia-Politica.pdf) in the first position to pursue a Master's degree in Political Science at the Institute of Social and Political Studies ([IESP-UERJ](https://www.iesp.uerj.br/)), starting in March 2025. This opportunity will allow me to contribute to impactful research, particularly in the application of Data Science and AI to the field.

<!-- **August 06, 2024**  
I've been accepted into the [AI Safety Fundamentals: Governance](https://aisafetyfundamentals.com/governance/?utm_campaign=Send+email%3A+Application+decisions&utm_content=Accept+participant&utm_medium=email_action&utm_source=customer.io) course, offered by [BlueDot Impact](https://bluedot.org/). I look forward to deepening my understanding of AI Governance, connecting with others in the field, and contributing to impactful work in AI Safety.

**August 01, 2024**  
I've started a new role as a Teaching Assistant for Quantitative Methods II, under the supervision of [Professor Jairo Nicolau, PhD](https://cpdoc.fgv.br/equipe/jaironicolau). My goal is to help students from the Social Sciences to learn useful skills for industry, academia, and government, such as programming and statistics.

**June 18, 2024**  
The research project of my undergraduate thesis, titled _The determinants of electoral success in legislative elections in Brazil: an approach using Bayesian multilevel models_, was approved with full marks. I am deeply grateful to Professors [Jaqueline Zulini, PhD](https://cpdoc.fgv.br/equipe/jaquelinezulini) and [Luiz Max Carvalho, PhD](https://emap.fgv.br/en/professors/luiz-max-fagundes-de-carvalho) for their outstanding supervision. I'm excited to dive deep into this research!

**June 18, 2024**  
I have been accepted to participate in the [Summer Institute in Computational Social Sciences](https://sicss.io/2024/fgv-ecmi-brazil/), hosted by [FGV ECMI](https://ecmi.fgv.br/en), in July 2024. It's an intensive two-week program that offers training in CSS techniques useful for academia, industry, and government.

**June 11, 2024**  
I have been accepted to participate in the next edition of [ML4Good](https://www.ml4good.org/courses/brasil-july-2024), in São Paulo, Brazil, in July 2024. It's a ten-day bootcamp that promotes upskilling in Deep Learning and AI Safety topics. -->