---
title: "✍🏼Publications"
---

## Papers

F. Lamarca, "As relações Executivo-Legislativo na Primeira República: uma análise das mensagens presidenciais ao Congresso (1910-1920)", *Mosaico*, vol. 13, no. 20, pp. 525-546, 2021. [[link]](https://hml-bibliotecadigital.fgv.br/ojs/index.php/mosaico/article/view/82665) [[pdf]](https://hml-bibliotecadigital.fgv.br/ojs/index.php/mosaico/article/view/82665/79990)

## Translations

J. Baker and I. Milligan, "Contagem e mineração de dados de investigação com Unix," translated by F. Lamarca, *Programming Historian em português*, Dec. 2021. [[link]](https://programminghistorian.org/pt/licoes/contagem-mineracao-dados-investigacao-unix)

F. Gibbs, "Instalação de Módulos Python com pip," translated by F. Lamarca, *Programming Historian em português*, Dec. 2021. [[link]](https://programminghistorian.org/pt/licoes/instalacao-modulos-python-pip)

W. Turkel and A. Crymble, "Reutilização de código e modularidade em Python," translated by F. Lamarca, *Programming Historian em português*, May 2021. [[link]](https://programminghistorian.org/pt/licoes/palavras-chave-contexto-usando-n-grams-python)

W. Turkel and A. Crymble, "Contagem de Frequências de Palavras com Python," translated by F. Lamarca, *Programming Historian em português*, Jan. 2022. [[link]](https://programminghistorian.org/pt/licoes/contar-frequencias-palavras-python)

W. Turkel and A. Crymble, "De HTML para Lista de Palavras (parte 1)," translated by F. Lamarca, *Programming Historian em português*, Oct. 2022. [[link]](https://programminghistorian.org/pt/licoes/HTML-lista-palavras-1)

W. Turkel and A. Crymble, "Normalização de Dados Textuais com Python," translated by F. Lamarca, *Programming Historian em português*, Oct. 2022. [[link]](https://programminghistorian.org/pt/licoes/normalizacao-dados-textuais-python)

W. Turkel and A. Crymble, "Criação e Visualização de Ficheiros HTML com Python," translated by F. Lamarca, *Programming Historian em português*, Oct. 2022. [[link]](https://programminghistorian.org/pt/licoes/criacao-visualizacao-ficheiros-html-python)

W. Turkel and A. Crymble, "Palavras-chave em Contexto (usando n-grams) com Python," translated by F. Lamarca, *Programming Historian em português*, Oct. 2022. [[link]](https://programminghistorian.org/pt/licoes/palavras-chave-contexto-usando-n-grams-python)

W. Turkel and A. Crymble, "Saída de Dados como um ficheiro HTML com Python," translated by F. Lamarca, *Programming Historian em português*, Oct. 2022. [[link]](https://programminghistorian.org/pt/licoes/saida-dados-ficheiro-html-python)

A. Crymble, "Download de Múltiplos Registros usando Query Strings," translated by F. Lamarca, *Programming Historian em português*, Nov. 2022. [[link]](https://programminghistorian.org/pt/licoes/download-multiplos-registros-query-strings)

W. Turkel and A. Crymble, "De HTML para Lista de Palavras (parte 2)," translated by F. Lamarca, *Programming Historian em português*, Dec. 2022. [[link]](https://programminghistorian.org/pt/licoes/HTML-lista-palavras-2)

