// GENERATED by scripts/build-map.py. Do not edit by hand; re-run the script:
//   python3 scripts/build-map.py
// Numbers behind Fig. 1 (src/components/figures/BrazilDots.astro).
import type { L } from './types';

export const fig1 = {
  /** Municipalities drawn, one dot each (the 2022 municipal map: 5,568 + Brasília + Fernando de Noronha). */
  count: 5570,
  /** Distinct dot positions after rounding to the 1000-unit grid; a few neighbouring seats share one. */
  points: 5547,
  variable: {
    en: 'turnout in the first round of the 2022 general election',
    'pt-br': 'comparecimento no 1º turno das eleições gerais de 2022',
  } as L,
  /** Turnout = voters who showed up / registered voters, per municipality (abroad excluded). */
  definition: {
    en: 'votes cast as a share of registered voters',
    'pt-br': 'comparecimento sobre eleitorado apto',
  } as L,
  source: 'TSE; IBGE',
  sources: [
    { name: 'TSE', what: 'turnout, 2022 1st round', url: 'https://resultados.tse.jus.br/oficial/ele2022/544/' },
    { name: 'IBGE', what: 'municipal seats (Localidades 2022)', url: 'https://geoftp.ibge.gov.br/organizacao_do_territorio/estrutura_territorial/localidades/Localidades_do_Brasil/2022/' },
  ],
  /** Quintiles, low → high, as proportions; a municipality is in bin i if from ≤ v < to (last bin inclusive). */
  bins: [
    { from: 0.594, to: 0.750, n: 1124 },
    { from: 0.750, to: 0.778, n: 1108 },
    { from: 0.778, to: 0.802, n: 1123 },
    { from: 0.802, to: 0.828, n: 1110 },
    { from: 0.828, to: 0.912, n: 1105 },
  ],
  min: 0.594,
  median: 0.790,
  max: 0.912,
  /** Pooled over all municipalities (sum of turnout / sum of electorate). */
  national: 0.792,
};
